### ISSUE TITLE
Decide on project structure

### ISSUE THREAD

**Issue by RichoDemus** [TSAR-Industries/slashgif#11]
So, we need to decide on how the project should be structured

Here is how it currently looks:
- api
- web
- service
- search-providers
  - google-image search

one thing we've talked about is splitting web into the slack-intregration and the dropwizard/application stuff. we've also talked about extracting the search-provider api from the api-project.
but that means that the api-project would only contain the service-api and then it's located in a weird spot. I think this is where the discussion is currently at:
- application (contains the dropwizard-stuff and the main-method)
- slack-integration (the endpoints and stuff for talking to slack)
- service-parent
  - service-api (just the interface/domain implemented by the service)
  - service
- search-providers
  - search-provider-api (just the interface/domain implemented by google-image-search)
  - google-image-search

What do you guys think?

**Comment by Osaou** [comment]
I think it would be a good idea to also group frontends in a module.
And also a common naming convention.
Like so:
- application
- frontends
  - api
  - slack-integration
- service-layer
  - api
  - services
- search-providers
  - api
  - google-image-search

Mjesh?
