### ISSUE TITLE
Use JitPack

### ISSUE THREAD

**Issue by Avecyclop** [TSAR-Industries/slashgif#6]
https://jitpack.io/

Use jitpack for dependencies like https://github.com/RichoDemus/guice-classpath-scanning

**Comment by RichoDemus** [comment]
It seems like jitpack doesn't really like it when a repository has multiple maven modules, you can only directly reference the parent pom and not any of the child poms. It still works but it's a bit ugly. So the solution will be to add a dependency to the parent and then use the code in the child pom. maven-dependency-plugin will complain so I added 2 ignores to our parent pom

**Comment by RichoDemus** [comment]
I've completed this, I'm just waiting for #2 to be approved before I create the pull request
