### ISSUE TITLE
Slack API prestudy

### ISSUE THREAD

**Issue by Osaou** [TSAR-Industries/slashgif#7]
How exactly do we integrate with the Slack API:s?
More specifically, which one(s) do we use?
- **Slash Commands** seem like a good fit for capturing user _input_, or maybe
- **Real Time Messaging API** to handle all integration (_input/output_).
- **Incoming Webhooks** might work for actually displaying content in the channel (_output_), or maybe
- **Web API** (method _chat.postMessage_) for that purpose...

Right now it's a bit unclear how to get the service to post _as a user_ (the user who issued the /gif command).

**Comment by Osaou** [comment]
When using **Slash Commands**, the issuing user's command is hidden (never displayed in chat), which makes it a good fit _if we could make the Slashgif bot post as that user_, but right now I'm leaning towards instead going the route of using **Real Time Messaging API** with an always-listening-bot acting on trigger words, or something like that.

For example:
_**Oskar:** butler, show me horns_
_**Butler:** Ok, here is a picture of horns..._

Then further down the line we could add non-gif functionality (WHAT!?) like:
_**Richard:** butler, how is the weather in älmhult?_
_**Butler:** It is currently 12 degrees celsius and raining in Älmhult, Sweden_

So, to begin with I propose we use _"butler"_ as a trigger word and some basic language parsing to show gifs, then build from there.
Oh, and maybe rename the entire thing to "Butler" or something, if we all like this idea.

**Comment by RichoDemus** [comment]
I totally agree, I also think it's funnier to "talk to the bot" than to simply use a slash-command
So if @Avecyclop agrees then we need to brainstorm a new name for this project :stuck_out_tongue_winking_eye:

**Comment by Osaou** [comment]
(Real world usage / aliasing / first attempts could be more like:

_**Oskar:** butler gif horns_)

**Comment by Osaou** [comment]
**_[Time passes... Meetings happen IRL...]_**

So then it's settled!
1. It shall now be named "But" - which may also be the _trigger word_ when integrating with the application via text (_"but, show me happy elks"_).
2. We will only need to use the _Real Time Messaging API_ to integrate with Slack, I believe.

Issue closed for the time being. May be re-opened if RTM API doesn't prove to be enough for our needs.
